name: Testar Meu Codigo Python

# Diz quando o teste deve rodar (ao enviar codigo para a branch main)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  executar-script:
    # Escolhe a maquina virtual (Ubuntu Linux)
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Copia os arquivos do repositorio para a maquina virtual
      - uses: actions/checkout@v4

      # Passo 2: Prepara o ambiente com o Python 3.10
      - name: Configurar Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Passo 3: Executa o seu script especifico
      - name: Rodar o exemplo_01.py
        run: |
          python atividade01.py
